### ISSUE TITLE
USER STORY: Add comment after selecting option

### ISSUE THREAD

**Issue by SiobhanP1** [SiobhanP1/love-running-project#3]
As a **user**, I can **add a comment after selecting an option** so that **I can give more detail regarding my choice**.

##Acceptance criteria
*Acceptance criteria 1: Add comment box appears after selecting an option and before submitting.
*Acceptance criteria 2: The comment box can hold text up to 200 characters. 
*Acceptance criteria 3: A prompt guides user to enter further helpful information including reason for choice and suggestions for options not currently offered.
*Acceptance criteria 4: The comment box is shown as 'optional'.

##Tasks
- [ ] Use HTML to build box and text spaces. 
- [ ] Add CSS styling in keeping with rest of page.
- [ ] Add prompt and title text.
- [ ] Add JavaScript to trigger action when user clicks 'Submit'. 
- [ ] Add Python to handle data (store in spreadsheet) when data submitted.
